/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Register_201_response_data.h"

namespace models {



Register_201_response_data::Register_201_response_data()
{
    m_AgentIsSet = false;
    m_ContractIsSet = false;
    m_FactionIsSet = false;
    m_ShipIsSet = false;
    m_Token = utility::conversions::to_string_t("");
    m_TokenIsSet = false;
}

Register_201_response_data::~Register_201_response_data()
{
}

void Register_201_response_data::validate()
{
    // TODO: implement validation
}

web::json::value Register_201_response_data::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_AgentIsSet)
    {
        val[utility::conversions::to_string_t(U("agent"))] = ModelBase::toJson(m_Agent);
    }
    if(m_ContractIsSet)
    {
        val[utility::conversions::to_string_t(U("contract"))] = ModelBase::toJson(m_Contract);
    }
    if(m_FactionIsSet)
    {
        val[utility::conversions::to_string_t(U("faction"))] = ModelBase::toJson(m_Faction);
    }
    if(m_ShipIsSet)
    {
        val[utility::conversions::to_string_t(U("ship"))] = ModelBase::toJson(m_Ship);
    }
    if(m_TokenIsSet)
    {
        val[utility::conversions::to_string_t(U("token"))] = ModelBase::toJson(m_Token);
    }

    return val;
}

bool Register_201_response_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("agent"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("agent")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Agent> refVal_setAgent;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAgent);
            setAgent(refVal_setAgent);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("contract"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("contract")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Contract> refVal_setContract;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContract);
            setContract(refVal_setContract);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("faction"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("faction")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Faction> refVal_setFaction;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFaction);
            setFaction(refVal_setFaction);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("ship"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("ship")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ship> refVal_setShip;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShip);
            setShip(refVal_setShip);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("token"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("token")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setToken;
            ok &= ModelBase::fromJson(fieldValue, refVal_setToken);
            setToken(refVal_setToken);
        }
    }
    return ok;
}

void Register_201_response_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_AgentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("agent")), m_Agent));
    }
    if(m_ContractIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("contract")), m_Contract));
    }
    if(m_FactionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("faction")), m_Faction));
    }
    if(m_ShipIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("ship")), m_Ship));
    }
    if(m_TokenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("token")), m_Token));
    }
}

bool Register_201_response_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("agent"))))
    {
        std::shared_ptr<Agent> refVal_setAgent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("agent"))), refVal_setAgent );
        setAgent(refVal_setAgent);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("contract"))))
    {
        std::shared_ptr<Contract> refVal_setContract;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("contract"))), refVal_setContract );
        setContract(refVal_setContract);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("faction"))))
    {
        std::shared_ptr<Faction> refVal_setFaction;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("faction"))), refVal_setFaction );
        setFaction(refVal_setFaction);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("ship"))))
    {
        std::shared_ptr<Ship> refVal_setShip;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("ship"))), refVal_setShip );
        setShip(refVal_setShip);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("token"))))
    {
        utility::string_t refVal_setToken;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("token"))), refVal_setToken );
        setToken(refVal_setToken);
    }
    return ok;
}

std::shared_ptr<Agent> Register_201_response_data::getAgent() const
{
    return m_Agent;
}

void Register_201_response_data::setAgent(const std::shared_ptr<Agent>& value)
{
    m_Agent = value;
    m_AgentIsSet = true;
}

bool Register_201_response_data::agentIsSet() const
{
    return m_AgentIsSet;
}

void Register_201_response_data::unsetAgent()
{
    m_AgentIsSet = false;
}
std::shared_ptr<Contract> Register_201_response_data::getContract() const
{
    return m_Contract;
}

void Register_201_response_data::setContract(const std::shared_ptr<Contract>& value)
{
    m_Contract = value;
    m_ContractIsSet = true;
}

bool Register_201_response_data::contractIsSet() const
{
    return m_ContractIsSet;
}

void Register_201_response_data::unsetContract()
{
    m_ContractIsSet = false;
}
std::shared_ptr<Faction> Register_201_response_data::getFaction() const
{
    return m_Faction;
}

void Register_201_response_data::setFaction(const std::shared_ptr<Faction>& value)
{
    m_Faction = value;
    m_FactionIsSet = true;
}

bool Register_201_response_data::factionIsSet() const
{
    return m_FactionIsSet;
}

void Register_201_response_data::unsetFaction()
{
    m_FactionIsSet = false;
}
std::shared_ptr<Ship> Register_201_response_data::getShip() const
{
    return m_Ship;
}

void Register_201_response_data::setShip(const std::shared_ptr<Ship>& value)
{
    m_Ship = value;
    m_ShipIsSet = true;
}

bool Register_201_response_data::shipIsSet() const
{
    return m_ShipIsSet;
}

void Register_201_response_data::unsetShip()
{
    m_ShipIsSet = false;
}
utility::string_t Register_201_response_data::getToken() const
{
    return m_Token;
}

void Register_201_response_data::setToken(const utility::string_t& value)
{
    m_Token = value;
    m_TokenIsSet = true;
}

bool Register_201_response_data::tokenIsSet() const
{
    return m_TokenIsSet;
}

void Register_201_response_data::unsetToken()
{
    m_TokenIsSet = false;
}
}


