/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ShipModificationTransaction.h"

namespace models {



ShipModificationTransaction::ShipModificationTransaction()
{
    m_WaypointSymbol = utility::conversions::to_string_t("");
    m_WaypointSymbolIsSet = false;
    m_ShipSymbol = utility::conversions::to_string_t("");
    m_ShipSymbolIsSet = false;
    m_TradeSymbol = utility::conversions::to_string_t("");
    m_TradeSymbolIsSet = false;
    m_TotalPrice = 0;
    m_TotalPriceIsSet = false;
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
}

ShipModificationTransaction::~ShipModificationTransaction()
{
}

void ShipModificationTransaction::validate()
{
    // TODO: implement validation
}

web::json::value ShipModificationTransaction::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_WaypointSymbolIsSet)
    {
        val[utility::conversions::to_string_t(U("waypointSymbol"))] = ModelBase::toJson(m_WaypointSymbol);
    }
    if(m_ShipSymbolIsSet)
    {
        val[utility::conversions::to_string_t(U("shipSymbol"))] = ModelBase::toJson(m_ShipSymbol);
    }
    if(m_TradeSymbolIsSet)
    {
        val[utility::conversions::to_string_t(U("tradeSymbol"))] = ModelBase::toJson(m_TradeSymbol);
    }
    if(m_TotalPriceIsSet)
    {
        val[utility::conversions::to_string_t(U("totalPrice"))] = ModelBase::toJson(m_TotalPrice);
    }
    if(m_TimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }

    return val;
}

bool ShipModificationTransaction::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("waypointSymbol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("waypointSymbol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWaypointSymbol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWaypointSymbol);
            setWaypointSymbol(refVal_setWaypointSymbol);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("shipSymbol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("shipSymbol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setShipSymbol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShipSymbol);
            setShipSymbol(refVal_setShipSymbol);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tradeSymbol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tradeSymbol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTradeSymbol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTradeSymbol);
            setTradeSymbol(refVal_setTradeSymbol);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("totalPrice"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("totalPrice")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalPrice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalPrice);
            setTotalPrice(refVal_setTotalPrice);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
        }
    }
    return ok;
}

void ShipModificationTransaction::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_WaypointSymbolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("waypointSymbol")), m_WaypointSymbol));
    }
    if(m_ShipSymbolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("shipSymbol")), m_ShipSymbol));
    }
    if(m_TradeSymbolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tradeSymbol")), m_TradeSymbol));
    }
    if(m_TotalPriceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("totalPrice")), m_TotalPrice));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("timestamp")), m_Timestamp));
    }
}

bool ShipModificationTransaction::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("waypointSymbol"))))
    {
        utility::string_t refVal_setWaypointSymbol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("waypointSymbol"))), refVal_setWaypointSymbol );
        setWaypointSymbol(refVal_setWaypointSymbol);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("shipSymbol"))))
    {
        utility::string_t refVal_setShipSymbol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("shipSymbol"))), refVal_setShipSymbol );
        setShipSymbol(refVal_setShipSymbol);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tradeSymbol"))))
    {
        utility::string_t refVal_setTradeSymbol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tradeSymbol"))), refVal_setTradeSymbol );
        setTradeSymbol(refVal_setTradeSymbol);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("totalPrice"))))
    {
        int32_t refVal_setTotalPrice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("totalPrice"))), refVal_setTotalPrice );
        setTotalPrice(refVal_setTotalPrice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    return ok;
}

utility::string_t ShipModificationTransaction::getWaypointSymbol() const
{
    return m_WaypointSymbol;
}

void ShipModificationTransaction::setWaypointSymbol(const utility::string_t& value)
{
    m_WaypointSymbol = value;
    m_WaypointSymbolIsSet = true;
}

bool ShipModificationTransaction::waypointSymbolIsSet() const
{
    return m_WaypointSymbolIsSet;
}

void ShipModificationTransaction::unsetWaypointSymbol()
{
    m_WaypointSymbolIsSet = false;
}
utility::string_t ShipModificationTransaction::getShipSymbol() const
{
    return m_ShipSymbol;
}

void ShipModificationTransaction::setShipSymbol(const utility::string_t& value)
{
    m_ShipSymbol = value;
    m_ShipSymbolIsSet = true;
}

bool ShipModificationTransaction::shipSymbolIsSet() const
{
    return m_ShipSymbolIsSet;
}

void ShipModificationTransaction::unsetShipSymbol()
{
    m_ShipSymbolIsSet = false;
}
utility::string_t ShipModificationTransaction::getTradeSymbol() const
{
    return m_TradeSymbol;
}

void ShipModificationTransaction::setTradeSymbol(const utility::string_t& value)
{
    m_TradeSymbol = value;
    m_TradeSymbolIsSet = true;
}

bool ShipModificationTransaction::tradeSymbolIsSet() const
{
    return m_TradeSymbolIsSet;
}

void ShipModificationTransaction::unsetTradeSymbol()
{
    m_TradeSymbolIsSet = false;
}
int32_t ShipModificationTransaction::getTotalPrice() const
{
    return m_TotalPrice;
}

void ShipModificationTransaction::setTotalPrice(int32_t value)
{
    m_TotalPrice = value;
    m_TotalPriceIsSet = true;
}

bool ShipModificationTransaction::totalPriceIsSet() const
{
    return m_TotalPriceIsSet;
}

void ShipModificationTransaction::unsetTotalPrice()
{
    m_TotalPriceIsSet = false;
}
utility::datetime ShipModificationTransaction::getTimestamp() const
{
    return m_Timestamp;
}

void ShipModificationTransaction::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool ShipModificationTransaction::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void ShipModificationTransaction::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
}


