/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ContractDeliverGood.h
 *
 * The details of a delivery contract. Includes the type of good, units needed, and the destination.
 */

#ifndef MODELS_ContractDeliverGood_H_
#define MODELS_ContractDeliverGood_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace models {


/// <summary>
/// The details of a delivery contract. Includes the type of good, units needed, and the destination.
/// </summary>
class  ContractDeliverGood
    : public ModelBase
{
public:
    ContractDeliverGood();
    virtual ~ContractDeliverGood();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ContractDeliverGood members

    /// <summary>
    /// The symbol of the trade good to deliver.
    /// </summary>
    utility::string_t getTradeSymbol() const;
    bool tradeSymbolIsSet() const;
    void unsetTradeSymbol();

    void setTradeSymbol(const utility::string_t& value);

    /// <summary>
    /// The destination where goods need to be delivered.
    /// </summary>
    utility::string_t getDestinationSymbol() const;
    bool destinationSymbolIsSet() const;
    void unsetDestinationSymbol();

    void setDestinationSymbol(const utility::string_t& value);

    /// <summary>
    /// The number of units that need to be delivered on this contract.
    /// </summary>
    int32_t getUnitsRequired() const;
    bool unitsRequiredIsSet() const;
    void unsetUnitsRequired();

    void setUnitsRequired(int32_t value);

    /// <summary>
    /// The number of units fulfilled on this contract.
    /// </summary>
    int32_t getUnitsFulfilled() const;
    bool unitsFulfilledIsSet() const;
    void unsetUnitsFulfilled();

    void setUnitsFulfilled(int32_t value);


protected:
    utility::string_t m_TradeSymbol;
    bool m_TradeSymbolIsSet;
    utility::string_t m_DestinationSymbol;
    bool m_DestinationSymbolIsSet;
    int32_t m_UnitsRequired;
    bool m_UnitsRequiredIsSet;
    int32_t m_UnitsFulfilled;
    bool m_UnitsFulfilledIsSet;
};


}

#endif /* MODELS_ContractDeliverGood_H_ */
