/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ContractPayment.h"

namespace models {



ContractPayment::ContractPayment()
{
    m_OnAccepted = 0;
    m_OnAcceptedIsSet = false;
    m_OnFulfilled = 0;
    m_OnFulfilledIsSet = false;
}

ContractPayment::~ContractPayment()
{
}

void ContractPayment::validate()
{
    // TODO: implement validation
}

web::json::value ContractPayment::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_OnAcceptedIsSet)
    {
        val[utility::conversions::to_string_t(U("onAccepted"))] = ModelBase::toJson(m_OnAccepted);
    }
    if(m_OnFulfilledIsSet)
    {
        val[utility::conversions::to_string_t(U("onFulfilled"))] = ModelBase::toJson(m_OnFulfilled);
    }

    return val;
}

bool ContractPayment::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("onAccepted"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("onAccepted")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setOnAccepted;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOnAccepted);
            setOnAccepted(refVal_setOnAccepted);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("onFulfilled"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("onFulfilled")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setOnFulfilled;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOnFulfilled);
            setOnFulfilled(refVal_setOnFulfilled);
        }
    }
    return ok;
}

void ContractPayment::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_OnAcceptedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("onAccepted")), m_OnAccepted));
    }
    if(m_OnFulfilledIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("onFulfilled")), m_OnFulfilled));
    }
}

bool ContractPayment::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("onAccepted"))))
    {
        int32_t refVal_setOnAccepted;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("onAccepted"))), refVal_setOnAccepted );
        setOnAccepted(refVal_setOnAccepted);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("onFulfilled"))))
    {
        int32_t refVal_setOnFulfilled;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("onFulfilled"))), refVal_setOnFulfilled );
        setOnFulfilled(refVal_setOnFulfilled);
    }
    return ok;
}

int32_t ContractPayment::getOnAccepted() const
{
    return m_OnAccepted;
}

void ContractPayment::setOnAccepted(int32_t value)
{
    m_OnAccepted = value;
    m_OnAcceptedIsSet = true;
}

bool ContractPayment::onAcceptedIsSet() const
{
    return m_OnAcceptedIsSet;
}

void ContractPayment::unsetOnAccepted()
{
    m_OnAcceptedIsSet = false;
}
int32_t ContractPayment::getOnFulfilled() const
{
    return m_OnFulfilled;
}

void ContractPayment::setOnFulfilled(int32_t value)
{
    m_OnFulfilled = value;
    m_OnFulfilledIsSet = true;
}

bool ContractPayment::onFulfilledIsSet() const
{
    return m_OnFulfilledIsSet;
}

void ContractPayment::unsetOnFulfilled()
{
    m_OnFulfilledIsSet = false;
}
}


