/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ShipFrame.h"

namespace models {



ShipFrame::ShipFrame()
{
    m_Symbol = utility::conversions::to_string_t("");
    m_SymbolIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Condition = 0;
    m_ConditionIsSet = false;
    m_ModuleSlots = 0;
    m_ModuleSlotsIsSet = false;
    m_MountingPoints = 0;
    m_MountingPointsIsSet = false;
    m_FuelCapacity = 0;
    m_FuelCapacityIsSet = false;
    m_RequirementsIsSet = false;
}

ShipFrame::~ShipFrame()
{
}

void ShipFrame::validate()
{
    // TODO: implement validation
}

web::json::value ShipFrame::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_SymbolIsSet)
    {
        val[utility::conversions::to_string_t(U("symbol"))] = ModelBase::toJson(m_Symbol);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_DescriptionIsSet)
    {
        val[utility::conversions::to_string_t(U("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_ConditionIsSet)
    {
        val[utility::conversions::to_string_t(U("condition"))] = ModelBase::toJson(m_Condition);
    }
    if(m_ModuleSlotsIsSet)
    {
        val[utility::conversions::to_string_t(U("moduleSlots"))] = ModelBase::toJson(m_ModuleSlots);
    }
    if(m_MountingPointsIsSet)
    {
        val[utility::conversions::to_string_t(U("mountingPoints"))] = ModelBase::toJson(m_MountingPoints);
    }
    if(m_FuelCapacityIsSet)
    {
        val[utility::conversions::to_string_t(U("fuelCapacity"))] = ModelBase::toJson(m_FuelCapacity);
    }
    if(m_RequirementsIsSet)
    {
        val[utility::conversions::to_string_t(U("requirements"))] = ModelBase::toJson(m_Requirements);
    }

    return val;
}

bool ShipFrame::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("symbol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("symbol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSymbol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSymbol);
            setSymbol(refVal_setSymbol);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("condition"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("condition")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCondition;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCondition);
            setCondition(refVal_setCondition);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("moduleSlots"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("moduleSlots")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setModuleSlots;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModuleSlots);
            setModuleSlots(refVal_setModuleSlots);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("mountingPoints"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("mountingPoints")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMountingPoints;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMountingPoints);
            setMountingPoints(refVal_setMountingPoints);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("fuelCapacity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("fuelCapacity")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFuelCapacity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFuelCapacity);
            setFuelCapacity(refVal_setFuelCapacity);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("requirements"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("requirements")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ShipRequirements> refVal_setRequirements;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRequirements);
            setRequirements(refVal_setRequirements);
        }
    }
    return ok;
}

void ShipFrame::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_SymbolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("symbol")), m_Symbol));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("description")), m_Description));
    }
    if(m_ConditionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("condition")), m_Condition));
    }
    if(m_ModuleSlotsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("moduleSlots")), m_ModuleSlots));
    }
    if(m_MountingPointsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("mountingPoints")), m_MountingPoints));
    }
    if(m_FuelCapacityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("fuelCapacity")), m_FuelCapacity));
    }
    if(m_RequirementsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("requirements")), m_Requirements));
    }
}

bool ShipFrame::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("symbol"))))
    {
        utility::string_t refVal_setSymbol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("symbol"))), refVal_setSymbol );
        setSymbol(refVal_setSymbol);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("condition"))))
    {
        int32_t refVal_setCondition;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("condition"))), refVal_setCondition );
        setCondition(refVal_setCondition);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("moduleSlots"))))
    {
        int32_t refVal_setModuleSlots;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("moduleSlots"))), refVal_setModuleSlots );
        setModuleSlots(refVal_setModuleSlots);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("mountingPoints"))))
    {
        int32_t refVal_setMountingPoints;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("mountingPoints"))), refVal_setMountingPoints );
        setMountingPoints(refVal_setMountingPoints);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("fuelCapacity"))))
    {
        int32_t refVal_setFuelCapacity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("fuelCapacity"))), refVal_setFuelCapacity );
        setFuelCapacity(refVal_setFuelCapacity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("requirements"))))
    {
        std::shared_ptr<ShipRequirements> refVal_setRequirements;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("requirements"))), refVal_setRequirements );
        setRequirements(refVal_setRequirements);
    }
    return ok;
}

utility::string_t ShipFrame::getSymbol() const
{
    return m_Symbol;
}

void ShipFrame::setSymbol(const utility::string_t& value)
{
    m_Symbol = value;
    m_SymbolIsSet = true;
}

bool ShipFrame::symbolIsSet() const
{
    return m_SymbolIsSet;
}

void ShipFrame::unsetSymbol()
{
    m_SymbolIsSet = false;
}
utility::string_t ShipFrame::getName() const
{
    return m_Name;
}

void ShipFrame::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool ShipFrame::nameIsSet() const
{
    return m_NameIsSet;
}

void ShipFrame::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t ShipFrame::getDescription() const
{
    return m_Description;
}

void ShipFrame::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool ShipFrame::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void ShipFrame::unsetDescription()
{
    m_DescriptionIsSet = false;
}
int32_t ShipFrame::getCondition() const
{
    return m_Condition;
}

void ShipFrame::setCondition(int32_t value)
{
    m_Condition = value;
    m_ConditionIsSet = true;
}

bool ShipFrame::conditionIsSet() const
{
    return m_ConditionIsSet;
}

void ShipFrame::unsetCondition()
{
    m_ConditionIsSet = false;
}
int32_t ShipFrame::getModuleSlots() const
{
    return m_ModuleSlots;
}

void ShipFrame::setModuleSlots(int32_t value)
{
    m_ModuleSlots = value;
    m_ModuleSlotsIsSet = true;
}

bool ShipFrame::moduleSlotsIsSet() const
{
    return m_ModuleSlotsIsSet;
}

void ShipFrame::unsetModuleSlots()
{
    m_ModuleSlotsIsSet = false;
}
int32_t ShipFrame::getMountingPoints() const
{
    return m_MountingPoints;
}

void ShipFrame::setMountingPoints(int32_t value)
{
    m_MountingPoints = value;
    m_MountingPointsIsSet = true;
}

bool ShipFrame::mountingPointsIsSet() const
{
    return m_MountingPointsIsSet;
}

void ShipFrame::unsetMountingPoints()
{
    m_MountingPointsIsSet = false;
}
int32_t ShipFrame::getFuelCapacity() const
{
    return m_FuelCapacity;
}

void ShipFrame::setFuelCapacity(int32_t value)
{
    m_FuelCapacity = value;
    m_FuelCapacityIsSet = true;
}

bool ShipFrame::fuelCapacityIsSet() const
{
    return m_FuelCapacityIsSet;
}

void ShipFrame::unsetFuelCapacity()
{
    m_FuelCapacityIsSet = false;
}
std::shared_ptr<ShipRequirements> ShipFrame::getRequirements() const
{
    return m_Requirements;
}

void ShipFrame::setRequirements(const std::shared_ptr<ShipRequirements>& value)
{
    m_Requirements = value;
    m_RequirementsIsSet = true;
}

bool ShipFrame::requirementsIsSet() const
{
    return m_RequirementsIsSet;
}

void ShipFrame::unsetRequirements()
{
    m_RequirementsIsSet = false;
}
}


