--[[
  SpaceTraders API

  SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

  The version of the OpenAPI document: 2.0.0
  Contact: joel@spacetraders.io
  Generated by: https://openapi-generator.tech
]]

-- market_trade_good class
local market_trade_good = {}
local market_trade_good_mt = {
	__name = "market_trade_good";
	__index = market_trade_good;
}

local function cast_market_trade_good(t)
	return setmetatable(t, market_trade_good_mt)
end

local function new_market_trade_good(symbol, type, trade_volume, supply, activity, purchase_price, sell_price)
	return cast_market_trade_good({
		["symbol"] = symbol;
		["type"] = type;
		["tradeVolume"] = trade_volume;
		["supply"] = supply;
		["activity"] = activity;
		["purchasePrice"] = purchase_price;
		["sellPrice"] = sell_price;
	})
end

return {
	cast = cast_market_trade_good;
	new = new_market_trade_good;
}
