--[[
  SpaceTraders API

  SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

  The version of the OpenAPI document: 2.0.0
  Contact: joel@spacetraders.io
  Generated by: https://openapi-generator.tech
]]

-- shipyard_transaction class
local shipyard_transaction = {}
local shipyard_transaction_mt = {
	__name = "shipyard_transaction";
	__index = shipyard_transaction;
}

local function cast_shipyard_transaction(t)
	return setmetatable(t, shipyard_transaction_mt)
end

local function new_shipyard_transaction(waypoint_symbol, ship_symbol, ship_type, price, agent_symbol, timestamp)
	return cast_shipyard_transaction({
		["waypointSymbol"] = waypoint_symbol;
		["shipSymbol"] = ship_symbol;
		["shipType"] = ship_type;
		["price"] = price;
		["agentSymbol"] = agent_symbol;
		["timestamp"] = timestamp;
	})
end

return {
	cast = cast_shipyard_transaction;
	new = new_shipyard_transaction;
}
