/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ContractPayment.h
 *
 * Payments for the contract.
 */

#ifndef MODELS_ContractPayment_H_
#define MODELS_ContractPayment_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace models {


/// <summary>
/// Payments for the contract.
/// </summary>
class  ContractPayment
    : public ModelBase
{
public:
    ContractPayment();
    virtual ~ContractPayment();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ContractPayment members

    /// <summary>
    /// The amount of credits received up front for accepting the contract.
    /// </summary>
    int32_t getOnAccepted() const;
    bool onAcceptedIsSet() const;
    void unsetOnAccepted();

    void setOnAccepted(int32_t value);

    /// <summary>
    /// The amount of credits received when the contract is fulfilled.
    /// </summary>
    int32_t getOnFulfilled() const;
    bool onFulfilledIsSet() const;
    void unsetOnFulfilled();

    void setOnFulfilled(int32_t value);


protected:
    int32_t m_OnAccepted;
    bool m_OnAcceptedIsSet;
    int32_t m_OnFulfilled;
    bool m_OnFulfilledIsSet;
};


}

#endif /* MODELS_ContractPayment_H_ */
