/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_status_200_response_stats.h
 *
 * 
 */

#ifndef MODELS_Get_status_200_response_stats_H_
#define MODELS_Get_status_200_response_stats_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace models {


/// <summary>
/// 
/// </summary>
class  Get_status_200_response_stats
    : public ModelBase
{
public:
    Get_status_200_response_stats();
    virtual ~Get_status_200_response_stats();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Get_status_200_response_stats members

    /// <summary>
    /// Number of registered agents in the game.
    /// </summary>
    int32_t getAgents() const;
    bool agentsIsSet() const;
    void unsetAgents();

    void setAgents(int32_t value);

    /// <summary>
    /// Total number of ships in the game.
    /// </summary>
    int32_t getShips() const;
    bool shipsIsSet() const;
    void unsetShips();

    void setShips(int32_t value);

    /// <summary>
    /// Total number of systems in the game.
    /// </summary>
    int32_t getSystems() const;
    bool systemsIsSet() const;
    void unsetSystems();

    void setSystems(int32_t value);

    /// <summary>
    /// Total number of waypoints in the game.
    /// </summary>
    int32_t getWaypoints() const;
    bool waypointsIsSet() const;
    void unsetWaypoints();

    void setWaypoints(int32_t value);


protected:
    int32_t m_Agents;
    bool m_AgentsIsSet;
    int32_t m_Ships;
    bool m_ShipsIsSet;
    int32_t m_Systems;
    bool m_SystemsIsSet;
    int32_t m_Waypoints;
    bool m_WaypointsIsSet;
};


}

#endif /* MODELS_Get_status_200_response_stats_H_ */
