/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ship_Refine_201_Response_data.h
 *
 * 
 */

#ifndef MODELS_Ship_Refine_201_Response_data_H_
#define MODELS_Ship_Refine_201_Response_data_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Cooldown.h"
#include "CppRestOpenAPIClient/model/Ship_Refine_201_Response_data_produced_inner.h"
#include "CppRestOpenAPIClient/model/ShipCargo.h"
#include <vector>

namespace models {

class ShipCargo;
class Cooldown;
class Ship_Refine_201_Response_data_produced_inner;

/// <summary>
/// 
/// </summary>
class  Ship_Refine_201_Response_data
    : public ModelBase
{
public:
    Ship_Refine_201_Response_data();
    virtual ~Ship_Refine_201_Response_data();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Ship_Refine_201_Response_data members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ShipCargo> getCargo() const;
    bool cargoIsSet() const;
    void unsetCargo();

    void setCargo(const std::shared_ptr<ShipCargo>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Cooldown> getCooldown() const;
    bool cooldownIsSet() const;
    void unsetCooldown();

    void setCooldown(const std::shared_ptr<Cooldown>& value);

    /// <summary>
    /// Goods that were produced by this refining process.
    /// </summary>
    std::vector<std::shared_ptr<Ship_Refine_201_Response_data_produced_inner>>& getProduced();
    bool producedIsSet() const;
    void unsetProduced();

    void setProduced(const std::vector<std::shared_ptr<Ship_Refine_201_Response_data_produced_inner>>& value);

    /// <summary>
    /// Goods that were consumed during this refining process.
    /// </summary>
    std::vector<std::shared_ptr<Ship_Refine_201_Response_data_produced_inner>>& getConsumed();
    bool consumedIsSet() const;
    void unsetConsumed();

    void setConsumed(const std::vector<std::shared_ptr<Ship_Refine_201_Response_data_produced_inner>>& value);


protected:
    std::shared_ptr<ShipCargo> m_Cargo;
    bool m_CargoIsSet;
    std::shared_ptr<Cooldown> m_Cooldown;
    bool m_CooldownIsSet;
    std::vector<std::shared_ptr<Ship_Refine_201_Response_data_produced_inner>> m_Produced;
    bool m_ProducedIsSet;
    std::vector<std::shared_ptr<Ship_Refine_201_Response_data_produced_inner>> m_Consumed;
    bool m_ConsumedIsSet;
};


}

#endif /* MODELS_Ship_Refine_201_Response_data_H_ */
