/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WaypointType.h
 *
 * The type of waypoint.
 */

#ifndef MODELS_WaypointType_H_
#define MODELS_WaypointType_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace models {

class  WaypointType
    : public ModelBase
{
public:
    WaypointType();
    virtual ~WaypointType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eWaypointType
    {
        WaypointType_PLANET,
        WaypointType_GAS_GIANT,
        WaypointType_MOON,
        WaypointType_ORBITAL_STATION,
        WaypointType_JUMP_GATE,
        WaypointType_ASTEROID_FIELD,
        WaypointType_ASTEROID,
        WaypointType_ENGINEERED_ASTEROID,
        WaypointType_ASTEROID_BASE,
        WaypointType_NEBULA,
        WaypointType_DEBRIS_FIELD,
        WaypointType_GRAVITY_WELL,
        WaypointType_ARTIFICIAL_GRAVITY_WELL,
        WaypointType_FUEL_STATION,
    };

    eWaypointType getValue() const;
    void setValue(eWaypointType const value);

    protected:
        eWaypointType m_value;
};

}

#endif /* MODELS_WaypointType_H_ */
